"""
CGA2D Cl(3,1) Functional Operations - Auto-generated

DO NOT EDIT MANUALLY - This file is generated by codegen/generate.py

Generated: 2025-12-08 12:54:03
Algebra: cga2d
Signature: (1, 1, 1, -1)
Blade count: 16

All functions are:
- Loop-free (fully expanded arithmetic)
- ONNX-compatible (only Add/Mul/Neg/Sub operations)
- Hard-coded (no Cayley table lookups)
"""

import torch
from torch import Tensor
from typing import Tuple


# =============================================================================
# Constants
# =============================================================================

BLADE_COUNT = 16
EUCLIDEAN_DIM = 2

# Blade indices by grade
GRADE_0_INDICES = (0,)
GRADE_1_INDICES = (1, 2, 3, 4)
GRADE_2_INDICES = (5, 6, 7, 8, 9, 10)
GRADE_3_INDICES = (11, 12, 13, 14)
GRADE_4_INDICES = (15,)

# Sparsity masks
UPGC_POINT_MASK = (1, 2, 3, 4)  # 4 components
MOTOR_MASK = (0, 5, 6, 7, 8, 9, 10)  # 7 components

# Reverse signs for all 16 blades
REVERSE_SIGNS = (1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1)

# Motor-specific reverse signs (7 components)
MOTOR_REVERSE_SIGNS = (1, -1, -1, -1, -1, -1, -1)

# =============================================================================
# Geometric Product (Full 16x16)
# =============================================================================

@torch.jit.script
def geometric_product_full(a: Tensor, b: Tensor) -> Tensor:
    """
    Compute the full geometric product of two multivectors.

    Args:
        a: Left operand, shape (..., 16)
        b: Right operand, shape (..., 16)

    Returns:
        Result multivector, shape (..., 16)

    Note:
        Fully expanded, no loops, ONNX compatible.
    """
    r0 = (
        a[..., 0] * b[..., 0] +
        a[..., 1] * b[..., 1] +
        a[..., 2] * b[..., 2] +
        a[..., 3] * b[..., 3] +
        -a[..., 4] * b[..., 4] +
        -a[..., 5] * b[..., 5] +
        -a[..., 6] * b[..., 6] +
        a[..., 7] * b[..., 7] +
        -a[..., 8] * b[..., 8] +
        a[..., 9] * b[..., 9] +
        a[..., 10] * b[..., 10] +
        -a[..., 11] * b[..., 11] +
        a[..., 12] * b[..., 12] +
        a[..., 13] * b[..., 13] +
        a[..., 14] * b[..., 14] +
        -a[..., 15] * b[..., 15]
    )
    r1 = (
        a[..., 0] * b[..., 1] +
        a[..., 1] * b[..., 0] +
        -a[..., 2] * b[..., 5] +
        -a[..., 3] * b[..., 6] +
        a[..., 4] * b[..., 7] +
        a[..., 5] * b[..., 2] +
        a[..., 6] * b[..., 3] +
        -a[..., 7] * b[..., 4] +
        -a[..., 8] * b[..., 11] +
        a[..., 9] * b[..., 12] +
        a[..., 10] * b[..., 13] +
        -a[..., 11] * b[..., 8] +
        a[..., 12] * b[..., 9] +
        a[..., 13] * b[..., 10] +
        -a[..., 14] * b[..., 15] +
        a[..., 15] * b[..., 14]
    )
    r2 = (
        a[..., 0] * b[..., 2] +
        a[..., 1] * b[..., 5] +
        a[..., 2] * b[..., 0] +
        -a[..., 3] * b[..., 8] +
        a[..., 4] * b[..., 9] +
        -a[..., 5] * b[..., 1] +
        a[..., 6] * b[..., 11] +
        -a[..., 7] * b[..., 12] +
        a[..., 8] * b[..., 3] +
        -a[..., 9] * b[..., 4] +
        a[..., 10] * b[..., 14] +
        a[..., 11] * b[..., 6] +
        -a[..., 12] * b[..., 7] +
        a[..., 13] * b[..., 15] +
        a[..., 14] * b[..., 10] +
        -a[..., 15] * b[..., 13]
    )
    r3 = (
        a[..., 0] * b[..., 3] +
        a[..., 1] * b[..., 6] +
        a[..., 2] * b[..., 8] +
        a[..., 3] * b[..., 0] +
        a[..., 4] * b[..., 10] +
        -a[..., 5] * b[..., 11] +
        -a[..., 6] * b[..., 1] +
        -a[..., 7] * b[..., 13] +
        -a[..., 8] * b[..., 2] +
        -a[..., 9] * b[..., 14] +
        -a[..., 10] * b[..., 4] +
        -a[..., 11] * b[..., 5] +
        -a[..., 12] * b[..., 15] +
        -a[..., 13] * b[..., 7] +
        -a[..., 14] * b[..., 9] +
        a[..., 15] * b[..., 12]
    )
    r4 = (
        a[..., 0] * b[..., 4] +
        a[..., 1] * b[..., 7] +
        a[..., 2] * b[..., 9] +
        a[..., 3] * b[..., 10] +
        a[..., 4] * b[..., 0] +
        -a[..., 5] * b[..., 12] +
        -a[..., 6] * b[..., 13] +
        -a[..., 7] * b[..., 1] +
        -a[..., 8] * b[..., 14] +
        -a[..., 9] * b[..., 2] +
        -a[..., 10] * b[..., 3] +
        -a[..., 11] * b[..., 15] +
        -a[..., 12] * b[..., 5] +
        -a[..., 13] * b[..., 6] +
        -a[..., 14] * b[..., 8] +
        a[..., 15] * b[..., 11]
    )
    r5 = (
        a[..., 0] * b[..., 5] +
        a[..., 1] * b[..., 2] +
        -a[..., 2] * b[..., 1] +
        a[..., 3] * b[..., 11] +
        -a[..., 4] * b[..., 12] +
        a[..., 5] * b[..., 0] +
        -a[..., 6] * b[..., 8] +
        a[..., 7] * b[..., 9] +
        a[..., 8] * b[..., 6] +
        -a[..., 9] * b[..., 7] +
        a[..., 10] * b[..., 15] +
        a[..., 11] * b[..., 3] +
        -a[..., 12] * b[..., 4] +
        a[..., 13] * b[..., 14] +
        -a[..., 14] * b[..., 13] +
        a[..., 15] * b[..., 10]
    )
    r6 = (
        a[..., 0] * b[..., 6] +
        a[..., 1] * b[..., 3] +
        -a[..., 2] * b[..., 11] +
        -a[..., 3] * b[..., 1] +
        -a[..., 4] * b[..., 13] +
        a[..., 5] * b[..., 8] +
        a[..., 6] * b[..., 0] +
        a[..., 7] * b[..., 10] +
        -a[..., 8] * b[..., 5] +
        -a[..., 9] * b[..., 15] +
        -a[..., 10] * b[..., 7] +
        -a[..., 11] * b[..., 2] +
        -a[..., 12] * b[..., 14] +
        -a[..., 13] * b[..., 4] +
        a[..., 14] * b[..., 12] +
        -a[..., 15] * b[..., 9]
    )
    r7 = (
        a[..., 0] * b[..., 7] +
        a[..., 1] * b[..., 4] +
        -a[..., 2] * b[..., 12] +
        -a[..., 3] * b[..., 13] +
        -a[..., 4] * b[..., 1] +
        a[..., 5] * b[..., 9] +
        a[..., 6] * b[..., 10] +
        a[..., 7] * b[..., 0] +
        -a[..., 8] * b[..., 15] +
        -a[..., 9] * b[..., 5] +
        -a[..., 10] * b[..., 6] +
        -a[..., 11] * b[..., 14] +
        -a[..., 12] * b[..., 2] +
        -a[..., 13] * b[..., 3] +
        a[..., 14] * b[..., 11] +
        -a[..., 15] * b[..., 8]
    )
    r8 = (
        a[..., 0] * b[..., 8] +
        a[..., 1] * b[..., 11] +
        a[..., 2] * b[..., 3] +
        -a[..., 3] * b[..., 2] +
        -a[..., 4] * b[..., 14] +
        -a[..., 5] * b[..., 6] +
        a[..., 6] * b[..., 5] +
        a[..., 7] * b[..., 15] +
        a[..., 8] * b[..., 0] +
        a[..., 9] * b[..., 10] +
        -a[..., 10] * b[..., 9] +
        a[..., 11] * b[..., 1] +
        a[..., 12] * b[..., 13] +
        -a[..., 13] * b[..., 12] +
        -a[..., 14] * b[..., 4] +
        a[..., 15] * b[..., 7]
    )
    r9 = (
        a[..., 0] * b[..., 9] +
        a[..., 1] * b[..., 12] +
        a[..., 2] * b[..., 4] +
        -a[..., 3] * b[..., 14] +
        -a[..., 4] * b[..., 2] +
        -a[..., 5] * b[..., 7] +
        a[..., 6] * b[..., 15] +
        a[..., 7] * b[..., 5] +
        a[..., 8] * b[..., 10] +
        a[..., 9] * b[..., 0] +
        -a[..., 10] * b[..., 8] +
        a[..., 11] * b[..., 13] +
        a[..., 12] * b[..., 1] +
        -a[..., 13] * b[..., 11] +
        -a[..., 14] * b[..., 3] +
        a[..., 15] * b[..., 6]
    )
    r10 = (
        a[..., 0] * b[..., 10] +
        a[..., 1] * b[..., 13] +
        a[..., 2] * b[..., 14] +
        a[..., 3] * b[..., 4] +
        -a[..., 4] * b[..., 3] +
        -a[..., 5] * b[..., 15] +
        -a[..., 6] * b[..., 7] +
        a[..., 7] * b[..., 6] +
        -a[..., 8] * b[..., 9] +
        a[..., 9] * b[..., 8] +
        a[..., 10] * b[..., 0] +
        -a[..., 11] * b[..., 12] +
        a[..., 12] * b[..., 11] +
        a[..., 13] * b[..., 1] +
        a[..., 14] * b[..., 2] +
        -a[..., 15] * b[..., 5]
    )
    r11 = (
        a[..., 0] * b[..., 11] +
        a[..., 1] * b[..., 8] +
        -a[..., 2] * b[..., 6] +
        a[..., 3] * b[..., 5] +
        a[..., 4] * b[..., 15] +
        a[..., 5] * b[..., 3] +
        -a[..., 6] * b[..., 2] +
        -a[..., 7] * b[..., 14] +
        a[..., 8] * b[..., 1] +
        a[..., 9] * b[..., 13] +
        -a[..., 10] * b[..., 12] +
        a[..., 11] * b[..., 0] +
        a[..., 12] * b[..., 10] +
        -a[..., 13] * b[..., 9] +
        a[..., 14] * b[..., 7] +
        -a[..., 15] * b[..., 4]
    )
    r12 = (
        a[..., 0] * b[..., 12] +
        a[..., 1] * b[..., 9] +
        -a[..., 2] * b[..., 7] +
        a[..., 3] * b[..., 15] +
        a[..., 4] * b[..., 5] +
        a[..., 5] * b[..., 4] +
        -a[..., 6] * b[..., 14] +
        -a[..., 7] * b[..., 2] +
        a[..., 8] * b[..., 13] +
        a[..., 9] * b[..., 1] +
        -a[..., 10] * b[..., 11] +
        a[..., 11] * b[..., 10] +
        a[..., 12] * b[..., 0] +
        -a[..., 13] * b[..., 8] +
        a[..., 14] * b[..., 6] +
        -a[..., 15] * b[..., 3]
    )
    r13 = (
        a[..., 0] * b[..., 13] +
        a[..., 1] * b[..., 10] +
        -a[..., 2] * b[..., 15] +
        -a[..., 3] * b[..., 7] +
        a[..., 4] * b[..., 6] +
        a[..., 5] * b[..., 14] +
        a[..., 6] * b[..., 4] +
        -a[..., 7] * b[..., 3] +
        -a[..., 8] * b[..., 12] +
        a[..., 9] * b[..., 11] +
        a[..., 10] * b[..., 1] +
        -a[..., 11] * b[..., 9] +
        a[..., 12] * b[..., 8] +
        a[..., 13] * b[..., 0] +
        -a[..., 14] * b[..., 5] +
        a[..., 15] * b[..., 2]
    )
    r14 = (
        a[..., 0] * b[..., 14] +
        a[..., 1] * b[..., 15] +
        a[..., 2] * b[..., 10] +
        -a[..., 3] * b[..., 9] +
        a[..., 4] * b[..., 8] +
        -a[..., 5] * b[..., 13] +
        a[..., 6] * b[..., 12] +
        -a[..., 7] * b[..., 11] +
        a[..., 8] * b[..., 4] +
        -a[..., 9] * b[..., 3] +
        a[..., 10] * b[..., 2] +
        a[..., 11] * b[..., 7] +
        -a[..., 12] * b[..., 6] +
        a[..., 13] * b[..., 5] +
        a[..., 14] * b[..., 0] +
        -a[..., 15] * b[..., 1]
    )
    r15 = (
        a[..., 0] * b[..., 15] +
        a[..., 1] * b[..., 14] +
        -a[..., 2] * b[..., 13] +
        a[..., 3] * b[..., 12] +
        -a[..., 4] * b[..., 11] +
        a[..., 5] * b[..., 10] +
        -a[..., 6] * b[..., 9] +
        a[..., 7] * b[..., 8] +
        a[..., 8] * b[..., 7] +
        -a[..., 9] * b[..., 6] +
        a[..., 10] * b[..., 5] +
        a[..., 11] * b[..., 4] +
        -a[..., 12] * b[..., 3] +
        a[..., 13] * b[..., 2] +
        -a[..., 14] * b[..., 1] +
        a[..., 15] * b[..., 0]
    )

    return torch.stack([
        r0, r1, r2, r3, r4, r5, r6, r7,
        r8, r9, r10, r11, r12, r13, r14, r15,
    ], dim=-1)

# =============================================================================
# Reverse Operation
# =============================================================================

@torch.jit.script
def reverse_full(mv: Tensor) -> Tensor:
    """
    Compute the reverse of a multivector.

    For grade k: coefficient *= (-1)^(k*(k-1)/2)

    Args:
        mv: Input multivector, shape (..., 16)

    Returns:
        Reversed multivector, shape (..., 16)
    """
    r0 = mv[..., 0]
    r1 = mv[..., 1]
    r2 = mv[..., 2]
    r3 = mv[..., 3]
    r4 = mv[..., 4]
    r5 = -mv[..., 5]
    r6 = -mv[..., 6]
    r7 = -mv[..., 7]
    r8 = -mv[..., 8]
    r9 = -mv[..., 9]
    r10 = -mv[..., 10]
    r11 = -mv[..., 11]
    r12 = -mv[..., 12]
    r13 = -mv[..., 13]
    r14 = -mv[..., 14]
    r15 = mv[..., 15]

    return torch.stack([
        r0, r1, r2, r3, r4, r5, r6, r7,
        r8, r9, r10, r11, r12, r13, r14, r15,
    ], dim=-1)

# =============================================================================
# Sparse Operations (Motor[7] x Point[4])
# =============================================================================

# Motor sparse indices: (0, 5, 6, 7, 8, 9, 10)
# Point sparse indices: (1, 2, 3, 4)

@torch.jit.script
def upgc_encode(x: Tensor) -> Tensor:
    """
    Encode 2D vector to UPGC point representation.

    X = n_o + x + 0.5|x|^2 * n_inf

    Where:
        n_o = 0.5 * (e- - e+)   -> coefficients: e+ = -0.5, e- = 0.5
        n_inf = e- + e+         -> coefficients: e+ = 1, e- = 1

    Args:
        x: 2D vector, shape (..., 2)

    Returns:
        UPGC point, shape (..., 4)
    """
    x1 = x[..., 0]
    x2 = x[..., 1]

    half_norm_sq = 0.5 * (x1 * x1 + x2 * x2)

    r0 = x1  # e1
    r1 = x2  # e2
    r2 = -0.5 + half_norm_sq  # e+
    r3 = 0.5 + half_norm_sq  # e-

    return torch.stack([r0, r1, r2, r3], dim=-1)


@torch.jit.script
def upgc_decode(point: Tensor) -> Tensor:
    """
    Decode UPGC point to 2D vector.

    Extracts the first 2 components (euclidean part).

    Args:
        point: UPGC point, shape (..., 4)

    Returns:
        2D vector, shape (..., 2)
    """
    return point[..., :2]


@torch.jit.script
def reverse_motor(motor: Tensor) -> Tensor:
    """
    Compute reverse of a motor (sparse 7-component version).

    Args:
        motor: Motor, shape (..., 7)

    Returns:
        Reversed motor, shape (..., 7)
    """
    r0 = motor[..., 0]  # 1: keep
    r1 = -motor[..., 1]  # e1e2: negate
    r2 = -motor[..., 2]  # e1e+: negate
    r3 = -motor[..., 3]  # e1e-: negate
    r4 = -motor[..., 4]  # e2e+: negate
    r5 = -motor[..., 5]  # e2e-: negate
    r6 = -motor[..., 6]  # e+e-: negate

    return torch.stack([r0, r1, r2, r3, r4, r5, r6], dim=-1)


@torch.jit.script
def sandwich_product_sparse(motor: Tensor, point: Tensor) -> Tensor:
    """
    Compute sparse sandwich product: M × X × M̃

    Optimized for:
        - Motor M: 7 components
        - Point X: 4 components
        - Output: 4 components

    Args:
        motor: Motor, shape (..., 7)
        point: UPGC point, shape (..., 4)

    Returns:
        Transformed point, shape (..., 4)

    Note:
        Total multiplications: 200 (vs 392 for naive)
    """
    # Motor components (sparse)
    m0 = motor[..., 0]  # 1
    m1 = motor[..., 1]  # e1e2
    m2 = motor[..., 2]  # e1e+
    m3 = motor[..., 3]  # e1e-
    m4 = motor[..., 4]  # e2e+
    m5 = motor[..., 5]  # e2e-
    m6 = motor[..., 6]  # e+e-

    # Point components (sparse)
    p0 = point[..., 0]  # e1
    p1 = point[..., 1]  # e2
    p2 = point[..., 2]  # e+
    p3 = point[..., 3]  # e-

    # Motor reverse
    mr0 = m0
    mr1 = -m1
    mr2 = -m2
    mr3 = -m3
    mr4 = -m4
    mr5 = -m5
    mr6 = -m6

    # Output r0 (e1): 25 terms
    r0 = (
        m0 * p0 * mr0 +
        -m0 * p1 * mr1 +
        -m0 * p2 * mr2 +
        m0 * p3 * mr3 +
        m1 * p0 * mr1 +
        m1 * p1 * mr0 +
        -m1 * p2 * mr4 +
        m1 * p3 * mr5 +
        m2 * p0 * mr2 +
        m2 * p1 * mr4 +
        m2 * p2 * mr0 +
        m2 * p3 * mr6 +
        -m3 * p0 * mr3 +
        -m3 * p1 * mr5 +
        -m3 * p2 * mr6 +
        -m3 * p3 * mr0 +
        -m4 * p0 * mr4 +
        m4 * p1 * mr2 +
        -m4 * p2 * mr1 +
        m5 * p0 * mr5 +
        -m5 * p1 * mr3 +
        m5 * p3 * mr1 +
        m6 * p0 * mr6 +
        -m6 * p2 * mr3 +
        m6 * p3 * mr2
    )

    # Output r1 (e2): 25 terms
    r1 = (
        m0 * p0 * mr1 +
        m0 * p1 * mr0 +
        -m0 * p2 * mr4 +
        m0 * p3 * mr5 +
        -m1 * p0 * mr0 +
        m1 * p1 * mr1 +
        m1 * p2 * mr2 +
        -m1 * p3 * mr3 +
        m2 * p0 * mr4 +
        -m2 * p1 * mr2 +
        m2 * p2 * mr1 +
        -m3 * p0 * mr5 +
        m3 * p1 * mr3 +
        -m3 * p3 * mr1 +
        m4 * p0 * mr2 +
        m4 * p1 * mr4 +
        m4 * p2 * mr0 +
        m4 * p3 * mr6 +
        -m5 * p0 * mr3 +
        -m5 * p1 * mr5 +
        -m5 * p2 * mr6 +
        -m5 * p3 * mr0 +
        m6 * p1 * mr6 +
        -m6 * p2 * mr5 +
        m6 * p3 * mr4
    )

    # Output r2 (e+): 25 terms
    r2 = (
        m0 * p0 * mr2 +
        m0 * p1 * mr4 +
        m0 * p2 * mr0 +
        m0 * p3 * mr6 +
        -m1 * p0 * mr4 +
        m1 * p1 * mr2 +
        -m1 * p2 * mr1 +
        -m2 * p0 * mr0 +
        m2 * p1 * mr1 +
        m2 * p2 * mr2 +
        -m2 * p3 * mr3 +
        -m3 * p0 * mr6 +
        m3 * p2 * mr3 +
        -m3 * p3 * mr2 +
        -m4 * p0 * mr1 +
        -m4 * p1 * mr0 +
        m4 * p2 * mr4 +
        -m4 * p3 * mr5 +
        -m5 * p1 * mr6 +
        m5 * p2 * mr5 +
        -m5 * p3 * mr4 +
        -m6 * p0 * mr3 +
        -m6 * p1 * mr5 +
        -m6 * p2 * mr6 +
        -m6 * p3 * mr0
    )

    # Output r3 (e-): 25 terms
    r3 = (
        m0 * p0 * mr3 +
        m0 * p1 * mr5 +
        m0 * p2 * mr6 +
        m0 * p3 * mr0 +
        -m1 * p0 * mr5 +
        m1 * p1 * mr3 +
        -m1 * p3 * mr1 +
        -m2 * p0 * mr6 +
        m2 * p2 * mr3 +
        -m2 * p3 * mr2 +
        -m3 * p0 * mr0 +
        m3 * p1 * mr1 +
        m3 * p2 * mr2 +
        -m3 * p3 * mr3 +
        -m4 * p1 * mr6 +
        m4 * p2 * mr5 +
        -m4 * p3 * mr4 +
        -m5 * p0 * mr1 +
        -m5 * p1 * mr0 +
        m5 * p2 * mr4 +
        -m5 * p3 * mr5 +
        -m6 * p0 * mr2 +
        -m6 * p1 * mr4 +
        -m6 * p2 * mr0 +
        -m6 * p3 * mr6
    )

    return torch.stack([r0, r1, r2, r3], dim=-1)

